# -*- coding: utf-8 -*-
"""NLP_practical1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_XSvSswYVCgieLjwPsoVdEg1dppsfEP
"""

name="NLP Lab"
hours=30
pi=3.14
topics=["Tokenization","POS tagging", "NER"]

hours=int(input("Enter Practice hours: "))
if hours>25:
  print("Sufficient hours for learning python")
else:
  print("Add more practice hours")

topics=["Variables","Loops","Functions","Lists"]
for topic in topics:
  print("Learning",topic)

def greet(student_name):
  return"Welcome to",student_name
print(greet("AL & NLP Lab"))