# -*- coding: utf-8 -*-
"""NLP_practical3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCyaX7VqFn7i42clAyJX9VKY2dvmv1vN
"""

import nltk

from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

nltk.download('punkt')

text="Natural language processing enables machines to understand human language."