# -*- coding: utf-8 -*-
"""NLP_Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRVwnlZo2mFE_n0qpq_urwAHNk7ohfQD
"""

#Import Libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer

#Download Required Datasets
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

#Sample test
text="Natural Language Processing enables machines to ungerstand human languages."

import nltk
nltk.download('punkt_tab')
tokens=word_tokenize(text)
tokens

#Stopword Removal
stop_words=set(stopwords.words('english'))
filtered_tokens=[word for word in tokens if word.lower() not in stop_words]

#Stemming
ps=PorterStemmer()
stemmed_tokens=[ps.stem(word) for word in filtered_tokens]

#Lemmatization
lemmatizer=WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(word) for word in filtered_tokens]

print("Tokens:",tokens)
print("Filtered Tokens:",filtered_tokens)
print("Stemmed Tokens:",stemmed_tokens)
print("Lemmatized Tokens:",lemmatized_tokens)