# -*- coding: utf-8 -*-
"""NLP_Basic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4gLGAA6qTdezs2lxnQdvR-7VCeTBPvN
"""

#Data type
name="NLP Lab"
hours=30
pi=3.14
topics=["Tokenization","POS tagging","NER"]

#Control Structures
if hours > 25:
  print("sufficient hours for learning python.")
else:
  print("Add more practise hours.")

#loop
for topic in topics:
  print("Learning:",topic)

#Function
def greet(student_name):
  return"Welcome to" + student_name
  print(greet("AI & NLP Lab"))